# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8728e322d1c651652d2d511b2a6d7a4fb6b9a05512c93aa889254b056ea9fac2681b5e0053f714f6b9d788dd0b4272fd5b6dee38a1d6a4e6b9f8d441f0179735

test:
  secret_key_base: e3e14938785c8e07456298b09981b2a01196af8bab920aaff7858629bfe9973314127d8758c0506bdf02d1d6f8d59d0926e4d9b18887ce90a8b2438595a68935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
